image: python:3.8-buster

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - sed -i 's,%%url%%,https://hpc-projects.pages.git-ce.rwth-aachen.de/nec-rwth/sx-aurora-offloading,g' mkdocs.yml
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - sed -i 's,%%url%%,https://hpc-projects.pages.git-ce.rwth-aachen.de/nec-rwth/sx-aurora-offloading,g' mkdocs.yml
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  only:
  - master
