image: python:3.8-buster

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - sed -i 's,%%url%%,https://hpc-projects.pages.git-ce.rwth-aachen.de/nec-rwth/sx-aurora-offloading,g' mkdocs.yml
    - sed -i 's,%%llvm%%,https://github.com/rwth-hpc/llvm-project,g' mkdocs.yml
    - sed -i 's,%%edit%%,https://git-ce.rwth-aachen.de/hpc-projects/nec-rwth/sx-aurora-offloading/-/edit/master/docs,g' mkdocs.yml
    - wget https://raw.githubusercontent.com/sx-aurora-dev/llvm-project/hpce/stable/README.md -O includes/readme.md && echo -e "#$(cat includes/readme.md)" > includes/readme.md && sed -i 's,# ,## ,g' includes/readme.md
    - mkdocs build --verbose --site-dir test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - sed -i 's,%%url%%,https://hpc-projects.pages.git-ce.rwth-aachen.de/nec-rwth/sx-aurora-offloading,g' mkdocs.yml
    - sed -i 's,%%llvm%%,https://github.com/rwth-hpc/llvm-project,g' mkdocs.yml
    - sed -i 's,%%edit%%,https://git-ce.rwth-aachen.de/hpc-projects/nec-rwth/sx-aurora-offloading/-/edit/master/docs,g' mkdocs.yml
    - wget https://raw.githubusercontent.com/sx-aurora-dev/llvm-project/hpce/stable/README.md -O includes/readme.md && echo -e "#$(cat includes/readme.md)" > includes/readme.md && sed -i 's,# ,## ,g' includes/readme.md
    - mkdocs build --verbose
  artifacts:
    paths:
      - public
  only:
    - master
