site_name: SX-Aurora Offloading
site_url: %%url%%
site_dir: public
theme:
    name: readthedocs
markdown_extensions:
    admonition: {}
nav:
    - Introduction: 'index.md'
    - Building the Project: 'building.md'
    - Source Transformation: 'source_transformation.md'
    - Build Wrapper: 'build_wrapper.md'
    - Usage: 'usage.md'
