site_name: SX-Aurora Offloading
copyright: © 2021 High Performance Computing at RWTH Aachen University
site_author: High Performance Computing at RWTH Aachen University
site_url: %%url%%
repo_url: %%llvm%%
repo_name: "llvm-project"
edit_uri: ""
site_dir: public
[data-md-color-scheme="rwth"] {
  --md-primary-fg-color:        #00549f;
  --md-primary-fg-color--light: #00549f;
  --md-primary-fg-color--dark:  #00549f;
}
theme:
  name: material
  features:
   - search.suggest
   - search.highlight
   - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: rwth
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  admonition: {}
plugins:
  - search
  - git-revision-date
nav:
  - Introduction: "index.md"
  - Building the Project: "building.md"
  - Build Wrapper: "build_wrapper.md"
  - Source Transformation: "source_transformation.md"
  - Usage: "usage.md"
  - Debugging: "debugging.md"
