site_name: SX-Aurora Offloading
site_url: %%url%%
repo_url: %%llvm%%
edit_uri: ""
site_dir: public
theme:
  name: material
markdown_extensions:
  admonition: {}
nav:
  - Introduction: "index.md"
  - Building the Project: "building.md"
  - Build Wrapper: "build_wrapper.md"
  - Source Transformation: "source_transformation.md"
  - Usage: "usage.md"
  - Debugging: "debugging.md"
